// src/app/layouts/Root.tsx
import { Outlet } from 'react-router';
import { Navigation } from '../components/Navigation';
import { Footer } from '../components/Footer';
import { WhatsAppFAB } from '../components/WhatsAppFAB';

export function Root() {
  return (
    <div className="min-h-screen" style={{ backgroundColor: 'var(--soft-background)' }}>
      <Navigation />
      <Outlet />
      <Footer />
      <WhatsAppFAB />
    </div>
  );
}

// src/app/layouts/root.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterOutlet } from '@angular/router';
import { NavigationComponent } from '../components/shared/navigation.component';
import { FooterComponent } from '../components/shared/footer.component';
import { WhatsAppFABComponent } from '../components/shared/whatsapp-fab.component';

@Component({
  selector: 'app-root-layout',
  standalone: true,
  imports: [
    CommonModule,
    RouterOutlet,
    NavigationComponent,
    FooterComponent,
    WhatsAppFABComponent,
  ],
  template: `
    <div class="min-h-screen root-container">
      <app-navigation></app-navigation>
      <router-outlet></router-outlet>
      <app-footer></app-footer>
      <app-whatsapp-fab></app-whatsapp-fab>
    </div>
  `,
  styles: [
    `
      .root-container {
        background-color: var(--soft-background);
      }
    `,
  ],
})
export class RootLayoutComponent {}
