// src/app/components/Navigation.tsx
import { useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router';
import { Menu, X } from 'lucide-react';

export function Navigation() {
  const [isScrolled, setIsScrolled] = useState(false);
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
  const navigate = useNavigate();

  useEffect(() => {
    const handleScroll = () => {
      setIsScrolled(window.scrollY > 50);
    };
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  return (
    <>
      <nav
        className={`fixed top-0 left-0 right-0 z-50 transition-all duration-200 ${
          isScrolled
            ? 'bg-white shadow-[0_2px_16px_rgba(13,43,78,0.08)]'
            : 'bg-transparent'
        }`}
        style={{ height: '70px' }}
      >
        <div className="max-w-[1280px] mx-auto px-6 md:px-12 lg:px-20 h-full flex items-center justify-between">
          {/* Logo */}
          <Link to="/" className="flex items-center gap-3">
            <div
              className="w-10 h-10 rounded-full flex items-center justify-center"
              style={{
                backgroundColor: isScrolled
                  ? 'var(--primary-blue)'
                  : 'rgba(255,255,255,0.2)',
              }}
            >
              <svg
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  d="M12 2L4 7V17L12 22L20 17V7L12 2Z"
                  stroke={isScrolled ? 'white' : 'white'}
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
                <path
                  d="M12 22V12"
                  stroke={isScrolled ? 'white' : 'white'}
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
              </svg>
            </div>
            <span
              className="font-bold text-lg"
              style={{
                color: isScrolled ? 'var(--dark-navy)' : 'white',
                fontFamily: 'var(--font-sans)',
              }}
            >
              PATHKIND LAB
            </span>
          </Link>

          {/* Desktop Navigation */}
          <div className="hidden md:flex items-center gap-9">
            <Link
              to="/#tests"
              className="transition-colors duration-200"
              style={{
                color: isScrolled ? 'var(--dark-navy)' : 'white',
                fontSize: '15px',
                fontWeight: '400',
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.color = 'var(--teal-accent)';
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.color = isScrolled
                  ? 'var(--dark-navy)'
                  : 'white';
              }}
            >
              Tests
            </Link>
            <Link
              to="/#packages"
              className="transition-colors duration-200"
              style={{
                color: isScrolled ? 'var(--dark-navy)' : 'white',
                fontSize: '15px',
                fontWeight: '400',
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.color = 'var(--teal-accent)';
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.color = isScrolled
                  ? 'var(--dark-navy)'
                  : 'white';
              }}
            >
              Packages
            </Link>
            <Link
              to="/contact"
              className="transition-colors duration-200"
              style={{
                color: isScrolled ? 'var(--dark-navy)' : 'white',
                fontSize: '15px',
                fontWeight: '400',
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.color = 'var(--teal-accent)';
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.color = isScrolled
                  ? 'var(--dark-navy)'
                  : 'white';
              }}
            >
              Contact
            </Link>
            <button
              onClick={() => navigate('/login')}
              className="px-4 transition-all duration-200"
              style={{
                height: '36px',
                borderRadius: '99px',
                backgroundColor: isScrolled
                  ? 'var(--primary-blue)'
                  : 'transparent',
                border: isScrolled ? 'none' : '1px solid white',
                color: 'white',
                fontSize: '14px',
                fontWeight: '500',
              }}
            >
              My Account
            </button>
          </div>

          {/* Mobile Menu Button */}
          <button
            className="md:hidden"
            onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
            style={{
              color: isScrolled ? 'var(--dark-navy)' : 'white',
            }}
          >
            <Menu size={24} strokeWidth={2} />
          </button>
        </div>
      </nav>

      {/* Mobile Menu Drawer */}
      {isMobileMenuOpen && (
        <>
          <div
            className="fixed inset-0 bg-black/50 z-40"
            onClick={() => setIsMobileMenuOpen(false)}
          />
          <div
            className="fixed top-0 right-0 bottom-0 w-64 bg-white z-50 p-6 flex flex-col"
            style={{
              animation: 'slideIn 200ms ease-out',
            }}
          >
            <button
              className="self-end mb-8"
              onClick={() => setIsMobileMenuOpen(false)}
              style={{ color: 'var(--dark-navy)' }}
            >
              <X size={24} />
            </button>
            <Link
              to="/#tests"
              className="py-4 border-b"
              style={{
                color: 'var(--dark-navy)',
                fontSize: '15px',
                borderColor: 'var(--border-color)',
              }}
              onClick={() => setIsMobileMenuOpen(false)}
            >
              Tests
            </Link>
            <Link
              to="/#packages"
              className="py-4 border-b"
              style={{
                color: 'var(--dark-navy)',
                fontSize: '15px',
                borderColor: 'var(--border-color)',
              }}
              onClick={() => setIsMobileMenuOpen(false)}
            >
              Packages
            </Link>
            <Link
              to="/contact"
              className="py-4 border-b"
              style={{
                color: 'var(--dark-navy)',
                fontSize: '15px',
                borderColor: 'var(--border-color)',
              }}
              onClick={() => setIsMobileMenuOpen(false)}
            >
              Contact
            </Link>
            <Link
              to="/login"
              className="py-4 border-b"
              style={{
                color: 'var(--dark-navy)',
                fontSize: '15px',
                borderColor: 'var(--border-color)',
              }}
              onClick={() => setIsMobileMenuOpen(false)}
            >
              My Account
            </Link>
          </div>
        </>
      )}

      <style>{`
        @keyframes slideIn {
          from {
            transform: translateX(100%);
          }
          to {
            transform: translateX(0);
          }
        }
      `}</style>
    </>
  );
}

// src/app/components/shared/navigation.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { Router } from '@angular/router';

@Component({
  selector: 'app-navigation',
  standalone: true,
  imports: [CommonModule, RouterLink],
  template: `
    <nav
      [ngStyle]="{ 'background-color': isScrolled ? 'white' : 'transparent',
                   'box-shadow': isScrolled ? '0 2px 16px rgba(13,43,78,0.08)' : 'none',
                   'transition': 'all 200ms ease' }"
      style="position: fixed; top: 0; left: 0; right: 0; z-index: 50; height: 70px;">
      <div style="max-width: 1280px; margin: 0 auto; padding: 0 20px; height: 100%; display: flex; align-items: center; justify-content: space-between;">
        
        <!-- Logo -->
        <a routerLink="/" style="display: flex; align-items: center; gap: 12px; text-decoration: none;">
          <div [ngStyle]="{ 'background-color': isScrolled ? 'var(--primary-blue)' : 'rgba(255,255,255,0.2)' }"
               style="width: 40px; height: 40px; border-radius: 50%; display: flex; align-items: center; justify-content: center;">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M12 2L4 7V17L12 22L20 17V7L12 2Z" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
              <path d="M12 22V12" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
          </div>
          <span [ngStyle]="{ 'color': isScrolled ? 'var(--dark-navy)' : 'white' }"
                style="font-weight: bold; font-size: 18px;">PATHKIND LAB</span>
        </a>

        <!-- Desktop Navigation -->
        <div style="display: none; gap: 36px; align-items: center;"
             [ngStyle]="{ 'display': 'flex' }" class="md-nav">
          <a routerLink="/#tests"
             [ngStyle]="{ 'color': isScrolled ? 'var(--dark-navy)' : 'white' }"
             (mouseenter)="onNavLinkHover($event, true)"
             (mouseleave)="onNavLinkHover($event, false)"
             style="text-decoration: none; transition: color 200ms; font-size: 15px; font-weight: 400;">
            Tests
          </a>
          <a routerLink="/#packages"
             [ngStyle]="{ 'color': isScrolled ? 'var(--dark-navy)' : 'white' }"
             (mouseenter)="onNavLinkHover($event, true)"
             (mouseleave)="onNavLinkHover($event, false)"
             style="text-decoration: none; transition: color 200ms; font-size: 15px; font-weight: 400;">
            Packages
          </a>
          <a routerLink="/contact"
             [ngStyle]="{ 'color': isScrolled ? 'var(--dark-navy)' : 'white' }"
             (mouseenter)="onNavLinkHover($event, true)"
             (mouseleave)="onNavLinkHover($event, false)"
             style="text-decoration: none; transition: color 200ms; font-size: 15px; font-weight: 400;">
            Contact
          </a>
          <button (click)="goToLogin()"
                  [ngStyle]="{ 'background-color': isScrolled ? 'var(--primary-blue)' : 'transparent',
                              'border': isScrolled ? 'none' : '1px solid white',
                              'color': 'white' }"
                  style="height: 36px; border-radius: 99px; padding: 0 16px; font-size: 14px; font-weight: 500; cursor: pointer; transition: all 200ms;">
            My Account
          </button>
        </div>

        <!-- Mobile Menu Button -->
        <button (click)="toggleMobileMenu()"
                [ngStyle]="{ 'color': isScrolled ? 'var(--dark-navy)' : 'white' }"
                style="display: flex; align-items: center; justify-content: center; border: none; background: none; cursor: pointer; font-size: 24px;">
          <span *ngIf="!isMobileMenuOpen">☰</span>
          <span *ngIf="isMobileMenuOpen">✕</span>
        </button>
      </div>
    </nav>

    <!-- Mobile Menu Overlay & Drawer -->
    <div *ngIf="isMobileMenuOpen"
         (click)="toggleMobileMenu()"
         style="position: fixed; inset: 0; background-color: rgba(0,0,0,0.5); z-index: 40;">
    </div>
    <div *ngIf="isMobileMenuOpen"
         style="position: fixed; top: 0; right: 0; bottom: 0; width: 256px; background-color: white; z-index: 50; padding: 24px; display: flex; flex-direction: column; animation: slideIn 200ms ease-out;">
      <button (click)="toggleMobileMenu()"
              style="align-self: flex-end; margin-bottom: 32px; border: none; background: none; cursor: pointer; color: var(--dark-navy); font-size: 24px;">
        ✕
      </button>
      <a routerLink="/#tests"
         (click)="toggleMobileMenu()"
         style="padding: 16px 0; border-bottom: 1px solid var(--border-color); color: var(--dark-navy); text-decoration: none; font-size: 15px;">
        Tests
      </a>
      <a routerLink="/#packages"
         (click)="toggleMobileMenu()"
         style="padding: 16px 0; border-bottom: 1px solid var(--border-color); color: var(--dark-navy); text-decoration: none; font-size: 15px;">
        Packages
      </a>
      <a routerLink="/contact"
         (click)="toggleMobileMenu()"
         style="padding: 16px 0; border-bottom: 1px solid var(--border-color); color: var(--dark-navy); text-decoration: none; font-size: 15px;">
        Contact
      </a>
      <a routerLink="/login"
         (click)="toggleMobileMenu()"
         style="padding: 16px 0; border-bottom: 1px solid var(--border-color); color: var(--dark-navy); text-decoration: none; font-size: 15px;">
        My Account
      </a>
    </div>

    <style>
      @keyframes slideIn {
        from {
          transform: translateX(100%);
        }
        to {
          transform: translateX(0);
        }
      }

      @media (min-width: 768px) {
        .md-nav {
          display: flex !important;
        }
      }
    </style>
  `,
  styles: [`
    :host {
      display: block;
    }
  `]
})
export class NavigationComponent implements OnInit, OnDestroy {
  isScrolled = false;
  isMobileMenuOpen = false;
  private scrollListener: (() => void) | null = null;

  constructor(private router: Router) {}

  ngOnInit() {
    this.scrollListener = () => {
      this.isScrolled = window.scrollY > 50;
    };
    window.addEventListener('scroll', this.scrollListener);
  }

  ngOnDestroy() {
    if (this.scrollListener) {
      window.removeEventListener('scroll', this.scrollListener);
    }
  }

  toggleMobileMenu() {
    this.isMobileMenuOpen = !this.isMobileMenuOpen;
  }

  goToLogin() {
    this.router.navigate(['/login']);
  }

  onNavLinkHover(event: MouseEvent, isHover: boolean) {
    const element = event.target as HTMLElement;
    if (isHover) {
      element.style.color = 'var(--teal-accent)';
    } else {
      element.style.color = this.isScrolled ? 'var(--dark-navy)' : 'white';
    }
  }
}
