// src/app/components/SectionHeader.tsx
interface SectionHeaderProps {
  label: string;
  title: string;
  subtitle?: string;
  align?: 'left' | 'center';
  viewAllLink?: boolean;
}

export function SectionHeader({
  label,
  title,
  subtitle,
  align = 'left',
  viewAllLink = false,
}: SectionHeaderProps) {
  return (
    <div
      className={`mb-8 md:mb-12 ${align === 'center' ? 'text-center' : ''} ${
        viewAllLink ? 'flex items-start justify-between' : ''
      }`}
    >
      <div className={align === 'center' ? 'mx-auto max-w-[560px]' : ''}>
        <div
          className={`flex items-center gap-3 mb-2 ${
            align === 'center' ? 'justify-center' : ''
          }`}
        >
          <div
            style={{
              width: '32px',
              height: '2px',
              backgroundColor: 'var(--teal-accent)',
            }}
          />
          <span
            style={{
              fontSize: '11px',
              fontFamily: 'var(--font-mono)',
              textTransform: 'uppercase',
              letterSpacing: '0.1em',
              color: 'var(--primary-blue)',
              fontWeight: '500',
            }}
          >
            {label}
          </span>
        </div>

        <h2
          style={{
            fontSize: 'clamp(28px, 4vw, 32px)',
            fontFamily: 'var(--font-sans)',
            fontWeight: '700',
            color: 'var(--dark-navy)',
            marginBottom: subtitle ? '8px' : '0',
          }}
        >
          {title}
        </h2>

        {subtitle && (
          <p
            style={{
              fontSize: '16px',
              color: 'var(--text-secondary)',
              lineHeight: '1.6',
            }}
          >
            {subtitle}
          </p>
        )}
      </div>

      {viewAllLink && (
        <a
          href="#all-tests"
          className="transition-colors duration-200 hover:underline whitespace-nowrap"
          style={{
            fontSize: '14px',
            color: 'var(--primary-blue)',
            fontWeight: '500',
          }}
        >
          View All Tests →
        </a>
      )}
    </div>
  );
}

// src/app/components/shared/section-header.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-section-header',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div [ngStyle]="{ 'text-align': align === 'center' ? 'center' : 'left',
                      'display': viewAllLink ? 'flex' : 'block',
                      'justify-content': viewAllLink ? 'space-between' : 'auto',
                      'align-items': viewAllLink ? 'flex-start' : 'auto' }"
         style="margin-bottom: 32px;">
      
      <div [ngStyle]="{ 'margin': align === 'center' ? '0 auto' : '0',
                       'max-width': align === 'center' ? '560px' : 'auto' }">
        
        <div style="display: flex; align-items: center; gap: 12px; margin-bottom: 8px;"
             [ngStyle]="{ 'justify-content': align === 'center' ? 'center' : 'flex-start' }">
          <div style="width: 32px; height: 2px; background-color: var(--teal-accent);" />
          <span style="font-size: 11px; font-family: var(--font-mono); text-transform: uppercase;
                       letter-spacing: 0.1em; color: var(--primary-blue); font-weight: 500;">
            {{ label }}
          </span>
        </div>

        <h2 style="font-size: clamp(28px, 4vw, 32px); font-family: var(--font-sans); font-weight: 700;
                   color: var(--dark-navy); margin-bottom: 8px;">
          {{ title }}
        </h2>

        <p *ngIf="subtitle"
           style="font-size: 16px; color: var(--text-secondary); line-height: 1.6;">
          {{ subtitle }}
        </p>
      </div>

      <a *ngIf="viewAllLink"
         href="#all-tests"
         style="font-size: 14px; color: var(--primary-blue); font-weight: 500; white-space: nowrap;
                 text-decoration: none; transition: text-decoration 200ms; cursor: pointer;">
        View All Tests →
      </a>
    </div>
  `,
  styles: [`
    :host {
      display: block;
    }
  `]
})
export class SectionHeaderComponent {
  @Input() label: string = '';
  @Input() title: string = '';
  @Input() subtitle?: string;
  @Input() align: 'left' | 'center' = 'left';
  @Input() viewAllLink: boolean = false;
}
