// src/app/components/category-chips.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

interface Category {
  id: string;
  name: string;
  icon: string;
}

@Component({
  selector: 'app-category-chips',
  standalone: true,
  imports: [CommonModule],
  template: `
    <section class="py-12">
      <div class="max-w-[1280px] mx-auto px-6 md:px-12 lg:px-20">
        <div class="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-4">
          <button
            *ngFor="let category of categories"
            class="p-4 rounded-xl transition-all duration-200 hover:shadow-md"
            [style.background-color]="category.id === activeCategory ? 'var(--primary-blue)' : 'white'"
            [style.border]="category.id === activeCategory ? 'none' : '1px solid var(--border-color)'"
            (click)="selectCategory(category.id)"
          >
            <div class="text-center">
              <div
                class="w-10 h-10 rounded-full flex items-center justify-center mx-auto mb-2"
                [style.background-color]="category.id === activeCategory ? 'rgba(255,255,255,0.2)' : 'var(--soft-background)'"
              >
                <span [style.color]="category.id === activeCategory ? 'white' : 'var(--primary-blue)'">
                  {{ category.icon }}
                </span>
              </div>
              <p
                style="font-size: 13px; font-weight: 600; margin: 0;"
                [style.color]="category.id === activeCategory ? 'white' : 'var(--text-primary)'"
              >
                {{ category.name }}
              </p>
            </div>
          </button>
        </div>
      </div>
    </section>
  `,
})
export class CategoryChipsComponent {
  activeCategory = 'all';

  categories: Category[] = [
    { id: 'all', name: 'All Tests', icon: '🏥' },
    { id: 'blood', name: 'Blood Tests', icon: '🩸' },
    { id: 'hormone', name: 'Hormones', icon: '⚗️' },
    { id: 'heart', name: 'Heart', icon: '❤️' },
    { id: 'diabetes', name: 'Diabetes', icon: '🩺' },
    { id: 'liver', name: 'Liver', icon: '🔬' },
  ];

  selectCategory(categoryId: string): void {
    this.activeCategory = categoryId;
  }
}

// src/app/components/CategoryChips.tsx
import { Heart, Activity, Droplet, TestTube, Stethoscope, Users } from 'lucide-react';
import { useState } from 'react';

const categories = [
  { id: 1, name: 'All Tests', icon: TestTube },
  { id: 2, name: 'Heart Health', icon: Heart },
  { id: 3, name: 'Blood Tests', icon: Droplet },
  { id: 4, name: 'Fitness', icon: Activity },
  { id: 5, name: 'General Health', icon: Stethoscope },
  { id: 6, name: 'Women\'s Health', icon: Users },
];

export function CategoryChips() {
  const [activeCategory, setActiveCategory] = useState(1);

  return (
    <section
      className="py-12"
      style={{ backgroundColor: 'var(--soft-background)' }}
    >
      <div className="max-w-[1280px] mx-auto px-6 md:px-12 lg:px-20">
        <h3
          className="mb-6"
          style={{
            fontSize: '16px',
            color: 'var(--text-primary)',
            fontWeight: '600',
          }}
        >
          Browse by Category
        </h3>

        <div className="flex gap-3 overflow-x-auto pb-2 no-scrollbar">
          {categories.map((category) => {
            const Icon = category.icon;
            const isActive = activeCategory === category.id;

            return (
              <button
                key={category.id}
                onClick={() => setActiveCategory(category.id)}
                className="flex items-center gap-2 px-4 py-2 whitespace-nowrap transition-all duration-150 flex-shrink-0"
                style={{
                  height: '40px',
                  borderRadius: '99px',
                  backgroundColor: isActive
                    ? 'var(--primary-blue)'
                    : 'white',
                  border: isActive
                    ? 'none'
                    : '1px solid var(--border-color)',
                  color: isActive ? 'white' : 'var(--dark-navy)',
                  fontSize: '13px',
                  fontWeight: '500',
                }}
                onMouseEnter={(e) => {
                  if (!isActive) {
                    e.currentTarget.style.backgroundColor =
                      'var(--badge-bg)';
                    e.currentTarget.style.borderColor = 'var(--primary-blue)';
                  }
                }}
                onMouseLeave={(e) => {
                  if (!isActive) {
                    e.currentTarget.style.backgroundColor = 'white';
                    e.currentTarget.style.borderColor = 'var(--border-color)';
                  }
                }}
              >
                <Icon
                  size={16}
                  style={{
                    color: isActive ? 'white' : 'var(--primary-blue)',
                  }}
                />
                {category.name}
              </button>
            );
          })}
        </div>
      </div>

      <style>{`
        .no-scrollbar::-webkit-scrollbar {
          display: none;
        }
        .no-scrollbar {
          -ms-overflow-style: none;
          scrollbar-width: none;
        }
      `}</style>
    </section>
  );
}
