// src/app/components/Testimonials.tsx
const testimonials = [
  {
    quote:
      'Excellent service! The home collection was punctual and professional. Got my reports within 12 hours. Highly recommend PATHKIND LAB.',
    name: 'Priya Sharma',
  },
  {
    quote:
      'Very impressed with the accuracy and speed of the reports. The staff was courteous and the entire process was seamless.',
    name: 'Rajesh Kumar',
  },
  {
    quote:
      'The prices are transparent and reasonable. No hidden charges. The WhatsApp booking made it super convenient for me.',
    name: 'Anita Desai',
  },
];

export function Testimonials() {
  return (
    <section
      className="py-16 md:py-24"
      style={{
        backgroundColor: 'var(--soft-background)',
      }}
    >
      <div className="max-w-[1280px] mx-auto px-6 md:px-12 lg:px-20">
        <div className="text-center mb-12">
          <div className="flex items-center gap-3 justify-center mb-2">
            <div
              style={{
                width: '32px',
                height: '2px',
                backgroundColor: 'var(--teal-accent)',
              }}
            />
            <span
              style={{
                fontSize: '11px',
                fontFamily: 'var(--font-mono)',
                textTransform: 'uppercase',
                letterSpacing: '0.1em',
                color: 'var(--primary-blue)',
                fontWeight: '500',
              }}
            >
              Testimonials
            </span>
            <div
              style={{
                width: '32px',
                height: '2px',
                backgroundColor: 'var(--teal-accent)',
              }}
            />
          </div>

          <h2
            style={{
              fontSize: 'clamp(28px, 4vw, 32px)',
              fontFamily: 'var(--font-sans)',
              fontWeight: '700',
              color: 'var(--dark-navy)',
            }}
          >
            What Our Patients Say
          </h2>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {testimonials.map((testimonial, index) => (
            <div
              key={index}
              className="bg-white p-6 relative"
              style={{
                borderRadius: '12px',
                boxShadow: '0 2px 12px rgba(13,43,78,0.06)',
              }}
            >
              {/* Quote Mark */}
              <div
                className="absolute top-4 left-4 opacity-20"
                style={{
                  fontFamily: 'var(--font-display)',
                  fontSize: '64px',
                  color: 'var(--teal-accent)',
                  lineHeight: '1',
                }}
              >
                "
              </div>

              <div className="relative pt-8">
                <p
                  className="mb-4 italic"
                  style={{
                    fontSize: '15px',
                    color: 'var(--text-primary)',
                    lineHeight: '1.6',
                  }}
                >
                  {testimonial.quote}
                </p>

                <div className="flex gap-1 mb-2">
                  {[...Array(5)].map((_, i) => (
                    <span
                      key={i}
                      style={{
                        fontSize: '14px',
                        color: '#FFC107',
                      }}
                    >
                      ★
                    </span>
                  ))}
                </div>

                <p
                  style={{
                    fontSize: '14px',
                    fontWeight: '700',
                    color: 'var(--dark-navy)',
                  }}
                >
                  {testimonial.name}
                </p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

// src/app/components/testimonials.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

interface Testimonial {
  name: string;
  role: string;
  content: string;
  rating: number;
  avatar: string;
}

@Component({
  selector: 'app-testimonials',
  standalone: true,
  imports: [CommonModule],
  template: `
    <section
      class="py-16 md:py-20"
      style="background-color: white;"
    >
      <div class="max-w-[1280px] mx-auto px-6 md:px-12 lg:px-20">
        <!-- Header -->
        <div class="mb-12 text-center">
          <div class="flex items-center gap-3 justify-center mb-4">
            <div
              class="w-8 h-0.5"
              style="background-color: var(--teal-accent);"
            ></div>
            <span
              class="uppercase tracking-widest"
              style="color: var(--teal-accent); font-size: 11px; font-family: var(--font-mono); letter-spacing: 0.1em;"
            >
              Testimonials
            </span>
            <div
              class="w-8 h-0.5"
              style="background-color: var(--teal-accent);"
            ></div>
          </div>

          <h2
            style="font-family: var(--font-display); font-size: clamp(32px, 4vw, 48px); font-weight: 700; color: var(--dark-navy); line-height: 1.2; margin-bottom: 16px;"
          >
            What Our Customers Say
          </h2>

          <p
            class="max-w-2xl mx-auto"
            style="font-size: 16px; color: var(--text-secondary); line-height: 1.6;"
          >
            Join thousands of satisfied customers who trust PATHKIND LAB
          </p>
        </div>

        <!-- Testimonials Grid -->
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <div
            *ngFor="let testimonial of testimonials"
            class="p-6 rounded-xl"
            style="background-color: var(--soft-background); border: 1px solid var(--border-color);"
          >
            <!-- Rating -->
            <div class="flex gap-1 mb-4">
              <span *ngFor="let i of [1,2,3,4,5]" style="font-size: 16px;">
                {{ i <= testimonial.rating ? '⭐' : '☆' }}
              </span>
            </div>

            <!-- Content -->
            <p
              class="mb-6"
              style="font-size: 15px; color: var(--text-primary); line-height: 1.6; margin: 0; font-style: italic;"
            >
              "{{ testimonial.content }}"
            </p>

            <!-- Author -->
            <div class="flex items-center gap-3">
              <div
                class="w-12 h-12 rounded-full flex items-center justify-center"
                style="background-color: var(--primary-blue);"
              >
                <span style="font-size: 20px; color: white;">{{ testimonial.avatar }}</span>
              </div>
              <div>
                <p
                  style="font-size: 14px; font-weight: 600; color: var(--dark-navy); margin: 0;"
                >
                  {{ testimonial.name }}
                </p>
                <p
                  style="font-size: 12px; color: var(--text-secondary); margin: 0;"
                >
                  {{ testimonial.role }}
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  `,
})
export class TestimonialsComponent {
  testimonials: Testimonial[] = [
    {
      name: 'Rajesh Kumar',
      role: 'Business Executive',
      content: 'Quick, professional, and very convenient. The home collection service is a lifesaver for my busy schedule.',
      rating: 5,
      avatar: '👨‍💼',
    },
    {
      name: 'Priya Sharma',
      role: 'Homemaker',
      content: 'Highly professional team. Results were accurate and delivered within the promised timeframe.',
      rating: 5,
      avatar: '👩‍🦰',
    },
    {
      name: 'Amit Patel',
      role: 'Software Engineer',
      content: 'Great experience! The online appointment booking and WhatsApp updates made everything super easy.',
      rating: 5,
      avatar: '👨‍💻',
    },
  ];
}
